# Nav
social:
  Github: https://github.com/a417420427
  简历: https://blog.zxueping.com/dist/index.html#/Resume

  附件: https://blog.zxueping.com/config/%E4%B8%AA%E4%BA%BA%E7%AE%80%E5%8E%86(%E5%BC%A0%E5%B8%86).pdf

# Background image, color
background: "url(https://cdn.jsdelivr.net/gh/frontendsophie/hexo-theme-autumn@1.0.0/source/img/button-bg.png) #f3f3f3"

# Favicon
favicon: avatar.jpeg

# SEO
keywords: "hexo, autumn"

# Widgets, enable at least one
widgets:
  category: enabled
  archive: enabled
  tag: enabled

# Set the first image in post to cover
auto_cover: true
